config/routes.rb
CsvTest::Application.routes.draw do
  resources :rushing_stats

end

app/models/rushing_stat.rb
class RushingStat < ActiveRecord::Base
  attr_accessible :name, :rushing_att, :rushing_att_avg, :rushing_long, :rushing_td, :rushing_yards
end

app/models/rushing_stats.rb
class RushingStats < ActiveRecord::Base
  attr_accessible :name, :rushing_att, :rushing_att_avg, :rushing_long, :rushing_td, :rushing_yards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/rushing_stats_controller.rb
class RushingStatsController < ApplicationController
  # GET /rushing_stats
  # GET /rushing_stats.json
  def index
    @rushing_stats = RushingStat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rushing_stats }
    end
  end

  # GET /rushing_stats/1
  # GET /rushing_stats/1.json
  def show
    @rushing_stat = RushingStat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rushing_stat }
    end
  end

  # GET /rushing_stats/new
  # GET /rushing_stats/new.json
  def new
    @rushing_stat = RushingStat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rushing_stat }
    end
  end

  # GET /rushing_stats/1/edit
  def edit
    @rushing_stat = RushingStat.find(params[:id])
  end

  # POST /rushing_stats
  # POST /rushing_stats.json
  def create
    @rushing_stat = RushingStat.new(params[:rushing_stat])

    respond_to do |format|
      if @rushing_stat.save
        format.html { redirect_to @rushing_stat, notice: 'Rushing stat was successfully created.' }
        format.json { render json: @rushing_stat, status: :created, location: @rushing_stat }
      else
        format.html { render action: "new" }
        format.json { render json: @rushing_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rushing_stats/1
  # PUT /rushing_stats/1.json
  def update
    @rushing_stat = RushingStat.find(params[:id])

    respond_to do |format|
      if @rushing_stat.update_attributes(params[:rushing_stat])
        format.html { redirect_to @rushing_stat, notice: 'Rushing stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rushing_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rushing_stats/1
  # DELETE /rushing_stats/1.json
  def destroy
    @rushing_stat = RushingStat.find(params[:id])
    @rushing_stat.destroy

    respond_to do |format|
      format.html { redirect_to rushing_stats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rushing_stats_helper.rb
module RushingStatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rushing_stats/_form.html.erb
<%= form_for(@rushing_stat) do |f| %>
  <% if @rushing_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rushing_stat.errors.count, "error") %> prohibited this rushing_stat from being saved:</h2>

      <ul>
      <% @rushing_stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rushing_att %><br />
    <%= f.number_field :rushing_att %>
  </div>
  <div class="field">
    <%= f.label :rushing_yards %><br />
    <%= f.number_field :rushing_yards %>
  </div>
  <div class="field">
    <%= f.label :rushing_att_avg %><br />
    <%= f.text_field :rushing_att_avg %>
  </div>
  <div class="field">
    <%= f.label :rushing_long %><br />
    <%= f.number_field :rushing_long %>
  </div>
  <div class="field">
    <%= f.label :rushing_td %><br />
    <%= f.number_field :rushing_td %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rushing_stats/edit.html.erb
<h1>Editing rushing_stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @rushing_stat %> |
<%= link_to 'Back', rushing_stats_path %>

app/views/rushing_stats/index.html.erb
<h1>Listing rushing_stats</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Rushing att</th>
    <th>Rushing yards</th>
    <th>Rushing att avg</th>
    <th>Rushing long</th>
    <th>Rushing td</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rushing_stats.each do |rushing_stat| %>
  <tr>
    <td><%= rushing_stat.name %></td>
    <td><%= rushing_stat.rushing_att %></td>
    <td><%= rushing_stat.rushing_yards %></td>
    <td><%= rushing_stat.rushing_att_avg %></td>
    <td><%= rushing_stat.rushing_long %></td>
    <td><%= rushing_stat.rushing_td %></td>
    <td><%= link_to 'Show', rushing_stat %></td>
    <td><%= link_to 'Edit', edit_rushing_stat_path(rushing_stat) %></td>
    <td><%= link_to 'Destroy', rushing_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rushing stat', new_rushing_stat_path %>

app/views/rushing_stats/new.html.erb
<h1>New rushing_stat</h1>

<%= render 'form' %>

<%= link_to 'Back', rushing_stats_path %>

app/views/rushing_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rushing_stat.name %>
</p>

<p>
  <b>Rushing att:</b>
  <%= @rushing_stat.rushing_att %>
</p>

<p>
  <b>Rushing yards:</b>
  <%= @rushing_stat.rushing_yards %>
</p>

<p>
  <b>Rushing att avg:</b>
  <%= @rushing_stat.rushing_att_avg %>
</p>

<p>
  <b>Rushing long:</b>
  <%= @rushing_stat.rushing_long %>
</p>

<p>
  <b>Rushing td:</b>
  <%= @rushing_stat.rushing_td %>
</p>


<%= link_to 'Edit', edit_rushing_stat_path(@rushing_stat) %> |
<%= link_to 'Back', rushing_stats_path %>